### ISSUE TITLE
Log File access denied for not admin local user

### ISSUE THREAD

**Issue by igrebel** [ravibpatel/AutoUpdater.NET#285]
Hi, is there any feature where I can disable to write log file?
I was try to set the Downloadpath in another Folder, but it still show me the error.
` Dim l_sLogFolder As String = Environment.GetFolderPath(Environment.SpecialFolder.Desktop) & "\Logs\"
    Dim di As DirectoryInfo = Directory.CreateDirectory(l_sLogFolder)
    AutoUpdater.DownloadPath = l_sLogFolder`

**Comment by ravibpatel** [comment]
Can you try the updated version from [here](https://ci.appveyor.com/api/buildjobs/mpj2tkxwag16uhnr/artifacts/AutoUpdater.NET-1.5.3.zip)? It should fix the issue.

**Comment by igrebel** [comment]
Still the same error... how can I just tell the updater, to not creater a log file?

**Comment by ravibpatel** [comment]
I will add it.

**Comment by igrebel** [comment]
Thank you very much

**Comment by igrebel** [comment]
> I will add it.

Can u add it in next few days?

**Comment by ravibpatel** [comment]
Sorry, I can't guarantee it but as soon as I get some free time I will do it.
